NamingRules:
  - InternalCode: '135ed515-ba04-468f-817b-559e86bbdcdc'
    Name: 'Business Hub Table'
    NamePattern: 'DH_T_{ModelObject.Name}_HUB'
    Scope: 'ModelObjectType'
  - InternalCode: 'b860fe9d-643f-40c8-8e21-b1b31d356d3f'
    Name: 'Business Link Table'
    NamePattern: 'DH_T_{ModelObject.Name}_LINK'
    Scope: 'ModelObjectType'
  - InternalCode: 'f8606b92-4b86-4db3-9c9b-99868c636654'
    Name: 'Business Satellite Table'
    NamePattern: 'DH_T_{ModelObject.Name}_SAT'
    Scope: 'ModelObjectType'
  - InternalCode: '585daed6-0f29-464b-8f0c-d47759ecfb6d'
    Name: 'Satellite Table'
    NamePattern: 'RDH_T_{ModelObject.Name}_SAT'
    Scope: 'ModelObjectType'
